version: 2
updates:
  - package-ecosystem: 'maven'
    directory: '/'
    schedule:
      interval: 'daily'
    ignore:
      - dependency-name: 'com.paritytrading.philadelphia:*'
        update-types: ['version-update:semver-major']
